# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 17:04

from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPage',
            fields=[
                ('page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True, primary_key=True, serialize=False,
                        to='wagtailcore.Page')),
                ('fragment', models.CharField(
                    blank=True,
                    help_text='(Optional) The id of the page fragment you'
                    'want to link to,\n i.e. the part after # in the URL',
                    max_length=255, null=True,
                    verbose_name='Fragment Identifier')),
            ],
            options={
                'verbose_name': 'Link Page',
                'verbose_name_plural': 'Link Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True, primary_key=True, serialize=False,
                        to='wagtailcore.Page')),
                ('body',
                    wagtail.wagtailcore.fields.StreamField(
                        (('section',
                          wagtail.wagtailcore.blocks.StructBlock(
                              (('type', wagtail.wagtailcore.blocks.CharBlock()),
                               ('title', wagtail.wagtailcore.blocks.CharBlock()),
                                  ('long_title', wagtail.wagtailcore.blocks.CharBlock(
                                  )),
                                  ('body', wagtail.wagtailcore.blocks.RichTextBlock()),
                                  ('items', wagtail.wagtailcore.blocks.ListBlock(
                                      wagtail.wagtailcore.blocks.StructBlock(
                                          (('type', wagtail.wagtailcore.blocks.CharBlock()),
                                           ('title', wagtail.wagtailcore.blocks.CharBlock()),
                                              ('long_title',
                                               wagtail.wagtailcore.blocks.CharBlock()),
                                              ('body', wagtail.wagtailcore.blocks.RichTextBlock(
                                              )),
                                              ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())),
                                          label='Item')))))),))
                 ),
            ],
            options={
                'verbose_name': 'Section Page',
                'verbose_name_plural': 'Section Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='linkpage',
            name='related_page',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+', to='wagtailcore.Page'),
        ),
    ]
