# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpage',
            name='fragment',
            field=models.CharField(blank=True, help_text='(Optional) The id of the page fragment you want to link to,\n         i.e. the part after # in the URL', max_length=255, null=True, verbose_name='Fragment Identifier'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('section', wagtail.wagtailcore.blocks.StructBlock((('type', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('long_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('body', wagtail.wagtailcore.blocks.RichTextBlock(classname='full', required=False)), ('items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('type', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('long_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('body', wagtail.wagtailcore.blocks.RichTextBlock(classname='full', required=False)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))), classname='full', label='Item')))))),)),
        ),
    ]
